on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true

      country:
        description: 'Select Country'
        required: true
        type: choice
        options:
        - CL
        - CO
        - MX
        - PE
        - EC
        - PA
      brand_one:
        default: 'null'
        description: 'Select Brand one'
        required: true
        type: choice
        options:
        - Esika
        - Cyzone
        - Lbel
      brand_two:
        default: 'null'
        description: 'Select Brand two'
        required: false
        type: choice
        options:
        - Esika
        - Cyzone
        - Lbel
      brand_three:
        default: 'null'
        description: 'Select Brand three'
        required: false
        type: choice
        options:
        - Esika
        - Cyzone
        - Lbel  
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
        - QAS
        - PRD
      tags:
        description: 'Add Tags to execute'
        default:  '''@CL and not @QAS'''
        required: true
        type: string
  workflow_call:

name: QA Workflow Release
env:
    country: ${{github.event.inputs.country}}
    brand_one: ${{github.event.inputs.brand_one}}
    brand_two: ${{github.event.inputs.brand_two}}
    brand_three: ${{github.event.inputs.brand_three}}
    environment : ${{github.event.inputs.environment}}   
jobs:
  executeE2eTests:
    runs-on: ubuntu-latest
    name: Execute E2E Tests
 
    
    steps:

      - name: Starting CLI testing
        shell: bash   
        run: |
            git clone https://github.com/prateekLambda/TestAction.git
            cd TestAction
              npm install
              node testMX.js
              curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
              chmod u+x hyperexecute
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config .hyperexecute.yaml
   
