name: QA Workflow Release
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true

      country:
        description: 'Select Country'
        required: true
        type: choice
        options:
        - CL
        - CO
        - MX
        - PE
        - EC
        - PA
      brand_one:
        default: 'null'
        description: 'Select Brand one'
        required: true
        type: choice
        options:
        - Esika
        - Cyzone
        - Lbel
        - not selected
      brand_two:
        default: 'null'
        description: 'Select Brand two'
        required: false
        type: choice
        options:
        - Esika
        - Cyzone
        - Lbel
        - not selected
      brand_three:
        default: 'null'
        description: 'Select Brand three'
        required: false
        type: choice
        options:
        - Esika
        - Cyzone
        - Lbel
        - not selected
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
        - QAS
        - PRD
      tags:
        description: 'Add Tags to execute'
        default:  '''@CL and not @QAS'''
        required: true
        type: string
  workflow_call:
env:
    country: ${{github.event.inputs.country}}
    brand_one: ${{github.event.inputs.brand_one}}
    brand_two: ${{github.event.inputs.brand_two}}
    brand_three: ${{github.event.inputs.brand_three}}
    environment: ${{github.event.inputs.environment}}
    NODE_VERSION: 16
jobs:
  executeE2eTests:
    name: Execute E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@main

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Starting CLI testing
        shell: bash
        run: |
              npm ci
              node testMX.js
              curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
              chmod u+x hyperexecute
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config .hyperexecute.yaml

